# Generated by Django 5.1 on 2024-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.CharField(choices=[('clean', 'Clean'), ('explicit', 'Explicit')], default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=250, unique_for_date='published_date'),
        ),
    ]
