# Generated by Django 5.1 on 2024-08-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.CharField(choices=[('pg', 'PG'), ('pg13', 'PG13'), ('17', '17'), ('18+', '18+')], default='PG', max_length=20),
        ),
    ]
